"""empty message

Revision ID: 86856c40cc09
Revises: 9c8db73915ce
Create Date: 2021-11-12 18:22:25.754029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86856c40cc09'
down_revision = '9c8db73915ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulties',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('turn_count', sa.Integer(), nullable=False),
                    sa.Column('multiplier', sa.Float, nullable=False),
                    sa.Column('level_id', sa.Integer, nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('levels',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('level_name', sa.String(
                        length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('runs',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('player_name', sa.String(
                        length=128), nullable=False),
                    sa.Column('score', sa.Float, nullable=False),
                    sa.Column('level_id', sa.Integer, nullable=True),
                    sa.Column('diff_id', sa.Integer, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('player_name')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('difficulties')
    op.drop_table('levels')
    op.drop_table('runs')
    # ### end Alembic commands ###
