"""empty message

Revision ID: d650c4904f30
Revises: 3a05ae7ae134
Create Date: 2021-11-15 15:20:06.577233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd650c4904f30'
down_revision = '3a05ae7ae134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'difficulties', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'runs', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'runs', 'difficulties', ['diff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_constraint(None, 'difficulties', type_='foreignkey')
    # ### end Alembic commands ###
