"""empty message

Revision ID: 3a05ae7ae134
Revises: 86856c40cc09
Create Date: 2021-11-15 15:07:37.910151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a05ae7ae134'
down_revision = '86856c40cc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_diff_level', 'difficulties', type_='foreignkey')
    op.drop_constraint('runs_player_name_key', 'runs', type_='unique')
    op.drop_constraint('runs_level_id_fkey', 'runs', type_='foreignkey')
    op.drop_constraint('runs_diff_id_fkey', 'runs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('runs_diff_id_fkey', 'runs', 'difficulties', ['diff_id'], ['id'])
    op.create_foreign_key('runs_level_id_fkey', 'runs', 'levels', ['level_id'], ['id'])
    op.create_unique_constraint('runs_player_name_key', 'runs', ['player_name'])
    op.create_foreign_key('fk_diff_level', 'difficulties', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###
